### ISSUE TITLE
Make pushing optional?

### ISSUE THREAD

**Issue by danielmai** [JeremySilverTongue/HistoryFlattening#3]
I tried to try out a change to _this_ repo, which I of course don't have push rights to, and I got this output:

```
$ python flatten.py
Creating local branch: 1.3-Exercise
Creating local branch: 1.2-Solution
Creating local branch: 1.2-Exercise
Creating local branch: 1.1-Solution
Creating local branch: 1.1-Exercise
Stashing
Saving snapshot of: 1.1-Exercise
Saving snapshot of: 1.1-Solution
Saving snapshot of: 1.2-Exercise
Saving snapshot of: 1.2-Solution
Saving snapshot of: 1.3-Exercise
Copying snapshot of: 1.1-Exercise
Copying snapshot of: 1.1-Solution
Copying snapshot of: 1.2-Exercise
Copying snapshot of: 1.2-Solution
Copying snapshot of: 1.3-Exercise
Popping
Pushing changes
Traceback (most recent call last):
  File "flatten.py", line 138, in <module>
    sys.exit(main())
  File "flatten.py", line 135, in main
    flattener.flatten()
  File "flatten.py", line 62, in flatten
    self.remote.push(all=True, prune = True)
  File "/usr/local/lib/python2.7/site-packages/git/remote.py", line 696, in push
    return self._get_push_info(proc, progress or RemoteProgress())
  File "/usr/local/lib/python2.7/site-packages/git/remote.py", line 601, in _get_push_info
    handle_process_output(proc, stdout_handler, progress_handler, finalize_process)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 212, in handle_process_output
    return finalizer(process)
  File "/usr/local/lib/python2.7/site-packages/git/util.py", line 155, in finalize_process
    proc.wait()
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 319, in wait
    raise GitCommandError(self.args, status, self.proc.stderr.read())
git.exc.GitCommandError: 'git push --porcelain --all --prune origin' returned with exit code 128
```

Of course, the push fails because I don't have push rights. In general though, could the push be optional? I wanted to run the script to see how the directory structure would be like after committing a change on the `develop` branch, but of course this scary error happens. And what if (heaven forbid) the script does something that I didn't want to push to the remote. I would like to review those changes before the push.

Also, it's weird that the script tells me [this message on line 64][1], even though it pushes:

```
print "Done! Review and commit/push the", self.student, "branch at your leisure."
```

[1]: 
https://github.com/JeremySilverTongue/HistoryFlattening/blob/a9835dc769434c2296addfaab5ed2e0cf9701193/flatten.py#L64

**Comment by JeremySilverTongue** [comment]
Good point. Commented out the automatic push, and added instructions on how to do it yourself.
